language: swift
osx_image: xcode10.1

script:
- xcodebuild clean build test -enableCodeCoverage YES -workspace Example/neovmUtils.xcworkspace -scheme neovmUtils-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6b496c8b-c3cd-4b23-bfd2-2f047ac303c3
