language: objective-c
osx_image: xcode10.1

install:
  - gem install xcpretty

script:
- xcodebuild clean build test -workspace Example/neovmUtils.xcworkspace -scheme neovmUtils-Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty -c
- pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF ios -J neovmUtils
  - rm Pods_neovmUtils_Tests.framework.coverage.txt
