language: objective-c
osx_image: xcode10.1

install:
  - gem install xcpretty

script:
- xcodebuild clean build test -enableCodeCoverage YES -workspace Example/neovmUtils.xcworkspace -scheme neovmUtils-Example -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
